@auth_token = Bearer {{$dotenv D365_TOKEN}}
@host = {{$dotenv D365_HOST}}

@TOOL_REPONSE_METHOD = GET
@TOOL_REPONSE_PATH = api/data/v9.2/opportunities?$filter=_customerid_value eq 4965d339-c1fb-e911-a813-000d3a3a19bc and statecode eq 0&$select=estimatedvalue

### Tool call 2. Step, get count of opportunities with statecode eq 0
{{TOOL_REPONSE_METHOD}} https://{{host}}/{{TOOL_REPONSE_PATH}}
Authorization: {{auth_token}}
